# This file is used to define the GitLab CI/CD pipeline for your project.
#
# By default the pipeline is disabled. When you are ready to enable CI in your
# project, rename this file to .gitlab-ci.yml (note the dot at the start of the
# filename) and commit and push the change. The pipeline will then be run and
# the results can be viewed on your repo's eng-git page from the
# 'Build > Pipelines' menu in the sidebar.
#
# GitLab CI/CD documentation: https://docs.gitlab.com/ee/ci/
# Syntax reference for this config file: https://docs.gitlab.com/ee/ci/yaml/index.html

stages:
  - host-test
  - target-build

host-test:
  stage: host-test
  image: harrymander/ence464-host-test-toolchain:latest
  script:
    - cmake -B build tests
    - cmake --build build --parallel
    - ctest --test-dir build --output-on-error --output-junit results.xml
  artifacts:
    when: always
    reports:
      junit: build/results.xml

target-build:
  stage: target-build
  image: harrymander/ence464-arm-toolchain:latest
  script:
    - |
      cmake -B build \
        --toolchain cmake/tm4c.cmake \
        -DENABLE_PROGRAM_TARGETS=off \
        -DBUILD_DEMOS=off \
        target
    - cmake --build build --parallel --target fitness-tracker
    - mv build/src/fitness-tracker .
  artifacts:
    name: fitness-tracker
    paths:
      - fitness-tracker
